---

- name: create user for Hadoop
  user:
    name: "{{ user_name }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    home: "{{hadoop_dest}}"

- name: Setting up Authorized key for hadoop user
  authorized_key:
    user: "{{ user_name }}"
    state: present
    key: " {{ lookup('file', lookup('env', 'home') + '/.ssh/id_rsa.pub') }} "


- name: Download Hadoop binary package
  unarchive:
    src: "{{hadoop_artifact}}"
    dest: "{{hadoop_dest}}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    remote_src: yes

- name:  
  lineinfile:
    path: /tmp/testfile
    line: '192.168.1.99 foo.lab.net foo'