---

- name: create user for Hadoop
  user:
    name: "{{ user_name }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    home: "{{ hadoop_dest }}/{{ user_name }}"
  tags: install, hadoop
    

- name: Setting up Authorized key for hadoop user
  authorized_key:
    user: "{{ user_name }}"
    state: present
    key: " {{ lookup('file', lookup('env', 'home') + '/.ssh/id_rsa.pub') }} "
  tags: install, hadoop


- name: Download Hadoop binary package from Artifact
  unarchive:
    src: "{{hadoop_artifact}}"
    dest: "{{ hadoop_dest }}/{{ user_name }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    remote_src: yes
  when: artifact
  tags: install, artifact, hadoop

- name: Download Hadoop binary package from binary
  unarchive:
    src: "{{hadoop_binary}}"
    dest: "{{ hadoop_dest }}/{{ user_name }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
  when: not artifact
  tags: install, hadoop

- name:  
  lineinfile:
    path: "{{hadoop_dest}}/{{ user_name }}/.bashrc_profile"
    line:  "{{ item }}"
  with_items:
    - ## JAVA env variables
    - export JAVA_HOME=/usr/java/default
    - export PATH=$PATH:$JAVA_HOME/bin
    - export CLASSPATH=.:$JAVA_HOME/jre/lib:$JAVA_HOME/lib:$JAVA_HOME/lib/tools.jar
    - ## HADOOP env variables
    - export HADOOP_HOME="{{hadoop_dest}}"/"{{user_name}}"
    - export HADOOP_COMMON_HOME=$HADOOP_HOME
    - export HADOOP_HDFS_HOME=$HADOOP_HOME
    - export HADOOP_MAPRED_HOME=$HADOOP_HOME
    - export HADOOP_YARN_HOME=$HADOOP_HOME
    - export HADOOP_OPTS="-Djava.library.path=$HADOOP_HOME/lib/native"
    - export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native
    - export PATH=$PATH:$HADOOP_HOME/sbin:$HADOOP_HOME/bin