---

- name: "Check Java is installed or not"
  shell: command -v java
  register: javaout
  ignore_errors: yes
  changed_when: false
  tags: install, java

- name: "Install Java from Artifact"
  yum:
    name: "{{ java_artifact }}"
    state: present
  when: artifact and javaout.rc > 0
  tags: install, artifact, java

- name: "Copy Java rpm"
  copy: 
    src: "{{ java_binary }}"
    dest: "/tmp/{{ java_binary }}"
  when: javaout.rc > 0 and not artifact  

- name: "Install java from Local Binary"
  yum:
    name: "/tmp/{{ java_binary }}"
    state: present
  when: javaout.rc > 0 and not artifact
  tags: install, java