---

#- name : "Download Java JDK RPM for Hadoop & Hbase"
#  get_url:
#    url: {{ java_version }}
#    dest: /tmp/java.rpm
#    mode: 0755

- name: "Check Java is installed or not"
  shell: command -v java
  register: javaout
  ignore_errors: yes
  tags: install, java

- name: "Install Java"
  yum:
    name: "{{ java_artifact }}"
    state: present
  when: artifact and javaout  > 0
  tags: install, artifact, java

- name: "Copy Java rpm"
  copy: 
    src: "{{ java_binary }}"
    dest: /tmp/"{{ java_binary }}"
  when: not artifact and javaout > 0

- name: "Install java"
  yum:
    name: /tmp/"{{ java_binary }}"
    state: present
  when: not artifact and javaout > 0
  tags: install, java