---

- name: Download HBase package from Artifact
  unarchive:
    src: "{{hbase_artifact}}.tar.gz"
    dest: "{{hbase_dest}}"
    remote_src: yes
    register: hbaseunzip
  when: artifact
  tags: install, artifact, hbase

- name: Unzip HBase binary package from binary
  unarchive:
    src: "{{hbase_binary}}.tar.gz"
    dest: "{{hbase_dest}}"
  when: not artifact
  register: hbaseunzip
  tags: install, hbase

- name: Move hbase directory
  shell: mv "{{hbase_dest}}/{{hbase_binary}}" "{{hbase_dest}}/hbase"
  when: hbaseunzip|changed
  tags: install, hbase

- name:
  lineinfile:
    path: "{{hbase_dest}}/hbase/conf/hbase-env.sh"
    line:  'export JAVA_HOME="{{hbase_java_export}}"'

- name: Copy Hbase-site.yml
  template:
    src: site.j2
    dest: "{{hbase_dest}}/hbase/conf/hbase-site.xml"